# Generated by configure from .in at Sun Jan 23 19:29:20 CET 2005

CC	= gcc
LD	= gcc

CFLAGS	= -g -Wall 
CFLAGS	+= -I. 
LDFLAGS	= libinterrupt.a
HEADERS = mythread.h queue.h


OBJS	= mythreadlib.o queue.o 

LIBS	= -lm -lrt

SRCS	= $(patsubst %.o,%.c,$(OBJS))

PRGS	= main

all: libinterrupt.a $(PRGS)

libinterrupt.a: interrupt.o
	ar -rv libinterrupt.a interrupt.o

%.o: %.c $(HEADERS)
	$(CC) $(CFLAGS) -c $*.c $(INCLUDE) -o $@ $(LIBS)

$(PRGS): $(OBJS)
$(PRGS): $(LIBS)
$(PRGS): % : %.o
	$(CC) $(CFLAGS) -o $@ $< $(OBJS) $(LDFLAGS) $(LIBS)

clean:
	-rm -f *.o *.a *~ $(PRGS)


rrf: interrupt.o
	ar -rv libinterrupt.a interrupt.o
	gcc -g -Wall  -I.  -c main.c  -o main.o -lm -lrt
	gcc -g -Wall  -I.  -c RRF.c  -o mythreadlib.o -lm -lrt
	gcc -g -Wall  -I.  -c queue.c  -o queue.o -lm -lrt
	gcc -g -Wall  -I.  -o main main.o mythreadlib.o queue.o  libinterrupt.a -lm -lrt


rr: interrupt.o
	ar -rv libinterrupt.a interrupt.o
	gcc -g -Wall  -I.  -c main.c  -o main.o -lm -lrt
	gcc -g -Wall  -I.  -c RR.c  -o mythreadlib.o -lm -lrt
	gcc -g -Wall  -I.  -c queue.c  -o queue.o -lm -lrt
	gcc -g -Wall  -I.  -o main main.o mythreadlib.o queue.o  libinterrupt.a -lm -lrt


rrfd: interrupt.o
	ar -rv libinterrupt.a interrupt.o
	gcc -g -Wall  -I.  -c main.c  -o main.o -lm -lrt
	gcc -g -Wall  -I.  -c RRFD.c  -o mythreadlib.o -lm -lrt
	gcc -g -Wall  -I.  -c queue.c  -o queue.o -lm -lrt
	gcc -g -Wall  -I.  -o main main.o mythreadlib.o queue.o  libinterrupt.a -lm -lrt

	

